env:
  browser: true
  commonjs: true
  es2021: true
  jest: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: 12

rules:
  consistent-return: off
  no-bitwise: off
  new-cap: off
  valid-typeof: off

