
version: "2"

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker

  redis:
    image: redis
    network_mode: host
    container_name: cache

  web:
    image: note-app
    container_name: api
    build: .
    env_file: .env
    ports:
      - "3001:3064"
    depends_on:
      - db
      - redis
